version: "3.7"
services:
   php:
    image: sashka74/php_alp_comp
    ports:
        - "9000:9000"
    volumes:
        - ~/docker-compose/www:/www
    networks:
      app_net:
        ipv4_address: 172.15.0.3

   nginx:
    image: sashka74/nginx_alp_comp
    ports:
        - "80:80"
    links:
        - "php"
    volumes:
         - ~/docker-compose/www:/www
    networks:
      app_net:
        ipv4_address: 172.15.0.2

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/24
