# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/8"
#  config.vm.box_check_update = false


  config.vm.define "log" do |log|
      log.vm.network  "private_network", ip: "192.168.120.10"
      log.vm.hostname = "log"  
      log.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
      log.vm.provision "shell", inline: <<-SHELL
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
          log.vm.provision "rsyslog", type: "shell" do |s|
                s.inline = <<-SHELL              
                        sed -i -r 's/#module.(load="imudp".)/module(load="imudp")/' /etc/rsyslog.conf
                        sed -i -r 's/#input.(type="imudp" port="514".)/input(type="imudp" port="514")/' /etc/rsyslog.conf
                        sed -i -r 's/#module.(load="imtcp".)/module(load="imtcp")/' /etc/rsyslog.conf
                        sed -i -r 's/#input.(type="imtcp" port="514".)/input(type="imtcp" port="514")/' /etc/rsyslog.conf
#                        sed -i '16 a $ModLoad imfile' /etc/rsyslog.conf
                        sed -i '17 a module(load="imfile")' /etc/rsyslog.conf
                        echo '\$template RemoteLogs, "/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"' >> /etc/rsyslog.conf
                        echo "*.* ?RemoteLogs" >> /etc/rsyslog.conf
                        echo "& ~" >> /etc/rsyslog.conf
                        echo '\$template HostAudit, "/var/log/rsyslog/%HOSTNAME%/audit.log\"' >> /etc/rsyslog.conf
                        echo "local6.* ?HostAudit" >> /etc/rsyslog.conf
                        systemctl restart rsyslog
                SHELL
         end
      end
  end

  config.vm.define "web" do |web|
      web.vm.network "private_network", ip: "192.168.120.11"
      web.vm.hostname = "web"  
      web.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
      web.vm.provision "shell", inline: <<-SHELL
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
          web.vm.provision "rsys", type: "shell" do |s|
                s.inline = <<-SHELL
                       setenforce 0
                       sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config
                       yum install -y nginx
                       sed -i 's/ *error.log;/error.log crit;/' /etc/nginx/nginx.conf
                       sed -i '8 a error_log syslog\x3Aserver\x3D192.168.120.10\x3B' /etc/nginx/nginx.conf
                       sed -i 's/    access_log/#    access_log/' /etc/nginx/nginx.conf
                       sed -i '24 a \\    access_log syslog:server=192.168.120.10;' /etc/nginx/nginx.conf
                       touch /etc/rsyslog.d/crit.conf
                       touch /etc/rsyslog.d/audit.conf
                       echo '*.crit @@192.168.120.10:514' >> /etc/rsyslog.d/crit.conf
                       echo '\$ModLoad imfile \n\$InputFileName /var/log/audit/audit.log \n\$InputFileTag tag_audit_log: \n\$InputFileStateFile audit_log \n\$InputFileSeverity info \n\$InputFileFacility local6 \n\$InputRunFileMonitor \n\*.*   @@192.168.120.10:514' >>  /etc/rsyslog.d/audit.conf
                       systemctl start nginx
                       systemctl enable nginx
#                       yum install policycoreutils setroubleshoot -y
#                       sudo audit2allow -a -M local
#                       sudo semodule -i local.pp
                       chmod 640 /var/log/audit/audit.log
                       systemctl restart rsyslog.service
                SHELL
          end 
      end
  end
end
