
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :centos => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end

          box.vm.provision "shell", inline: <<-SHELL
#          mkdir -p ~root/.ssh
#          cp ~vagrant/.ssh/auth* ~root/.ssh
           yum install -y redhat-lsb-core wget gcc rpmdevtools rpm-build createrepo yum-utils
           sudo -u vagrant wget https://nginx.org/packages/centos/7/SRPMS/nginx-1.14.1-1.el7_4.ngx.src.rpm
           sudo -u vagrant rpm -i nginx-1.14.1-1.el7_4.ngx.src.rpm
           sudo -u vagrant wget https://www.openssl.org/source/latest.tar.gz           
           sudo -u vagrant tar -xvf latest.tar.gz
           yum-builddep rpmbuild/SPECS/nginx.spec -y
           sed -i "109 a  --with-openssl=/home/vagrant/openssl-1.1.1g" rpmbuild/SPECS/nginx.spec
           sed -i -r -e 's/--with-openssl/    --with-openssl/' rpmbuild/SPECS/nginx.spec
           sed -i "111 d" rpmbuild/SPECS/nginx.spec
           sudo -u vagrant rpmbuild -bb rpmbuild/SPECS/nginx.spec
           yum localinstall -y rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm
           systemctl start nginx
           mkdir /usr/share/nginx/html/repo
           cp rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm /usr/share/nginx/html/repo/
           wget http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm -O /usr/share/nginx/html/repo/percona-release-0.1-6.noarch.rpm
           createrepo /usr/share/nginx/html/repo/
           sed -i "10 a  autoindex on;" /etc/nginx/conf.d/default.conf
           nginx -s reload
           touch /etc/yum.repos.d/otus.repo
           echo "[otus] \nname=otus-linux \nbaseurl=http://localhost/repo \ngpgcheck=0 \nenabled=1" >> /etc/yum.repos.d/otus.repo
           yum install percona-release -y
      SHELL

      end
  end
end

